site_name: Remit
site_url: https://zyrouge.github.io/remit-docs/
docs_dir: ./docs
repo_url: https://github.com/zyrouge/remit-docs
repo_name: zyrouge/remit-docs
edit_uri: edit/main/docs/

theme:
    name: material
    # logo: assets/logo.png
    favicon: assets/favicon.png
    palette:
        scheme: slate
        primary: purple
        accent: purple
    font:
        text: Fira Sans
        code: Fira Code
    features:
        - navigation.top
        - content.action.edit

markdown_extensions:
    - admonition
    - toc:
          permalink: true
    - tables

copyright: Licensed under GPL-3.0
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/zyrouge/remit-docs
